* Demos

** DONE RF, Replay - Clicker

Perform a replay attack on a unprotected clicker.

- Directory: [[file:rf-clicker/]]

** DONE RF, Soft-TEMPEST - Etherify

Exfiltrate a secret in Morse Code through a Soft-Tempest covert-channel based on Ethernet link mode.

- Prerequisites :
  1. One computer connected with an Ethernet cable to an internet box OR two
     computers connected with an Ethernet cable to each others.
  2. One SDR (from RTL-SDR to USRP).
  3. GQRX and sudo permissions.
- Directory: [[file:rf-etherify/]]

** DONE GSM, Spoofing - OpenBTS

- Hardware :
  - Ettus USRP B210
- Software :
  - Ubuntu 16.04
  - OpenBTS

Demo using OpenBTS and a USRP B210 or B200mini SDR to build a rogue GSM base station.

** NEXT RF: Fingerprinting

The original was this one : https://www.rtl-sdr.com/fingerprinting-electronic-devices-via-their-rf-emissions-with-an-rtl-sdr-and-imagemagick/
Maybe you can find something better, this is nice because it is extremely simple.

** NEXT RF: TempestSDR

The original was this one : https://www.rtl-sdr.com/tempestsdr-a-sdr-tool-for-eavesdropping-on-computer-screens-via-unintentionally-radiated-rf/
It is a bit annoying to use but it works.
Alternatively, there is =gr-tempest= in GNURadio but I never really tried it.
It seems that Giovanni also tried : https://github.com/martinmarinov/TempestSDR

** PROG Wi-Fi: WEP

** PROG Wi-Fi: WPA

** PROG Wi-Fi: Evil-Twin
