* Demos

** DONE RF, Replay - Clicker

Perform a replay attack on a unprotected clicker.

- Directory: [[file:rf-clicker/]]

** DONE RF, Soft-TEMPEST - Etherify

Exfiltrate a secret in Morse Code through a Soft-Tempest covert-channel based on Ethernet link mode.

- Prerequisites :
  1. One computer connected with an Ethernet cable to an internet box OR two
     computers connected with an Ethernet cable to each others.
  2. One SDR (from RTL-SDR to USRP).
  3. GQRX and sudo permissions.
- Directory: [[file:rf-etherify/]]

** DONE GSM, Spoofing - OpenBTS

- Hardware :
  - Ettus USRP B210
- Software :
  - Ubuntu 16.04
  - OpenBTS

Demo using OpenBTS and a USRP B210 or B200mini SDR to build a rogue GSM base station.

** DONE Wi-Fi: WEP

In this demo, you will generate traffic (using ARP replay) on a WEP-protected
Wi-Fi network in order to capture IVs and perform an offline cracking of the
WEP key. Every steps are programmed in a [[file:wifi-wep/Makefile][=Makefile=]].

List of the setup:
- Software:
  - =aircrack-ng=
  - =NetworkManager=
- Hardware:
  - Attacker aircrack-compatible Wi-Fi dongle (here, [[https://www.zyxel.com/fr/fr/products/wifi-extender/dual-band-wireless-ac1200-usb-adapter-nwd6605][ZyXEL NWD6605]] ([[https://www.amazon.fr/Zyxel-AC1200-Adaptateur-Wi-Fi-NWD6605/dp/B00D9EZSO2][Amazon]]) with the [[https://github.com/aircrack-ng/rtl8812au][rtl8812au]] driver).
  - Victim AP-compatible interface (here, Wi-Fi card of a Lenovo Thinkpad T460 laptop).

** DONE Wi-Fi: WPA

In this demo, you will setup a WPA2 protected network with a victim
authenticated to it. As an attacker, you will start listening to the traffic to
capture a 4-way handshake while sending deauthentication request to the
victim. Hence, you will be able to perform an offline dictionary attack on the
4-way handshake to retrieve the WPA 2 key.

Every steps are programmed in a [[file:wifi-wpa/Makefile][=Makefile=]].

List of the setup:
- Software:
  - =aircrack-ng=
  - =NetworkManager=
- Hardware:
  - Attacker aircrack-compatible Wi-Fi dongle (here, [[https://www.zyxel.com/fr/fr/products/wifi-extender/dual-band-wireless-ac1200-usb-adapter-nwd6605][ZyXEL NWD6605]] ([[https://www.amazon.fr/Zyxel-AC1200-Adaptateur-Wi-Fi-NWD6605/dp/B00D9EZSO2][Amazon]]) with the [[https://github.com/aircrack-ng/rtl8812au][rtl8812au]] driver).
  - Victim AP-compatible interface (here, a COTS ASUS Wi-Fi access point).
  - Victim STA-compatible interface (here, Wi-Fi card of a Lenovo Thinkpad T460 laptop).

** DONE Wi-Fi: Evil-Twin

Setup a fake Wi-Fi network with the same name as a legitimate Wi-Fi network,
creating an evil twin. The goal is to make the victim client connect to the
evil twin instead of the legitimate Wi-Fi AP.

This demo succeed once, but failed another. Some parameters could be tuned to
make it more reliable. Once it will be done, it would be great to setup the
transparent forwarding of the victim data to the internet, to make the evil
twin stealth (currently, the victim will loose connection to the internet).

** NEXT RF: Fingerprinting

The original was this one : https://www.rtl-sdr.com/fingerprinting-electronic-devices-via-their-rf-emissions-with-an-rtl-sdr-and-imagemagick/
Maybe you can find something better, this is nice because it is extremely simple.

