# -*- mode: ruby -*-

# The "2" in Vagrant.configure configures the configuration version (we support
# older styles for backwards compatibility). Please don't change it unless you
# know what you're doing.
Vagrant.configure("2") do |config|
  # Requires a box with Ubuntu Xenial 16.04 from https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial32"

  # Share the host demo folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder.
  config.vm.synced_folder ".", "/home/vagrant/openbts-demo"

  # Provider-specific configuration.
  config.vm.provider "virtualbox" do |vb|
      # Enable USB 3.0.
      vb.customize ["modifyvm", :id, "--usb", "on"]
      vb.customize ["modifyvm", :id, "--usbxhci", "on"]
      # Allow any USB device to be grabbed by the VM (hence, the USRP).
      vb.customize ['usbfilter', 'add', '0', '--target', :id, '--name', 'All', '--vendorid', '', '--productid', '']
  end

  # Enable provisioning with a Makefile run as the user.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get install make
    cd ~/openbts-demo
    make guest-install
  SHELL
end
